services:
  camtgrtsp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camTGrtsp
    ports:
      - "127.0.0.1:8000:8000"  # Web UI только на localhost
    volumes:
      - ./config.json:/app/config.json  # Конфиг монтируем вне образа
      - ./output:/app/output            # Папка с детекциями
      - ./alarm:/app/alarm              # Папка с алармами
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.75"
